apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-v2-0
  labels:
    app: recommendation-engine
    version: v2.0
spec:
  replicas: 10
  selector:
    matchLabels:
      app: recommendation-engine
      version: v2.0
  template:
    metadata:
      labels:
        app: recommendation-engine
        version: v2.0
    spec:
      containers:
      - name: rec-engine
        image: nginx:1.28
        ports:
        - containerPort: 80
